### ISSUE TITLE
Hope enhancement in AlertDialog

### ISSUE THREAD

**Issue by xmflsdede** [Prototik/HoloEverywhere#49] opened 2012-08-29 03:01 UTC
First I would like to say Holo Everywhere is awesome!!

When I use AlertDialog, the dialog panel and text are in holo theme. However, the button is left to the android build-in theme, which is not so pretty when I run my app on Android 2.3.3.

And I wish there would be an enhancement in AlertDialog. Or, maybe I've just missed sth to fulfill my dream?...

**Comment by Prototik** [comment] 2012-08-29 05:50
HoloAlertDialogBuilder still very raw, and for some reason do not want to develop.
As an alternative, I can offer you my fork HoloEverywhere, there AlertDialog rewritten, and everything looks correct.

Sorry for bad english:)

**Comment by ChristopheVersieux** [comment] 2012-08-29 06:08
Hello Ptototik, 

the reason I cannot develop myself is simply a new house and some family life.
I would be glad to add your HoloEverywhere fork and improve the lib. I just need to know if I can add it manually, and how I can I give you the credits you deserve (a link to your profile in the edit comment?)

Or maybe you plan to create a pull request?

Thank a lot.

**Comment by Prototik** [comment] 2012-08-29 06:13
Hello, Christophe!

Okay, i'm create pull request in the near future, I think, today.

The link to the profile ... No, because this is a open-source, then everyone gives as much as can.

**Comment by xmflsdede** [comment] 2012-08-29 08:11
Thanks a lot guys!
Oh another issue: how can holo everywhere support no title bar and full screen mode, just like oringinal Theme.Black.NoTitleBar.Fullscreen in android 2.x? I just want some full screen things..

**Comment by Prototik** [comment] 2012-08-29 08:15
Oh, i'm yet prepare commit.
In brief: you should define custom theme with inheritance of the desired HoloEverywhere themes and also specify a couple of attributes.

**Comment by xmflsdede** [comment] 2012-08-30 00:26
Thank you again for all your answers! Best regards!

**Comment by Prototik** [comment] 2012-08-30 03:56
Christophe, close this issue.

**Comment by tanwwg** [comment] 2012-08-30 04:55
Hi, I tried the new fork from Prototik but it doesn't work properly at all. The dialogs occupy the full screen on emulator 2.3.3. Please revert.

**Comment by Prototik** [comment] 2012-08-30 04:58
Try to place the content of dialogue dimensions WrapContent.
And HoloAlertDialogBuilder not removed.

**Comment by tanwwg** [comment] 2012-08-30 05:48
I did, doesn't work.

**Comment by Prototik** [comment] 2012-08-30 06:09
Strangely, my AlertDialog compresses to the size of the content.
Can you show a layout for the dialog?

**Comment by tanwwg** [comment] 2012-08-30 08:19
Actually, on trying to simplify everything, here's a piece of code that
reproduces the error (note, using ActionBarSherlock as well):

HoloAlertDialogBuilder builder = new HoloAlertDialogBuilder(ctx);
        builder.setMessage(ctx.getString(resId));
        builder.setTitle("Help");

```
    /*
    builder.setPositiveButton("OK", new
```

DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {
                dialogInterface.dismiss();
            }
        });
        */
        builder.show();

**Comment by tanwwg** [comment] 2012-08-30 08:19
Sorry, replace HoloAlertDialogBuilder with the new AlertDialog.Builder.

**Closed as completed** 2012-09-04 14:48 UTC
